language: php
php:
  - 7.1.9

before_install:
    # disable xdebug if available
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    # disable default memory limit
    - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI

#addons:
#  apt:
#    packages:
#      - parallel

install:
  - composer install

#script:
#  # Run tests in parallel (utterly pointless!)
#  - ls -d tests/*.php | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && exit 1);'
