language: php
php:
  - 7.1.9

before_install:
    # disable xdebug if available
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    # disable default memory limit
    - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI

install:
  - composer install
